name: C CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install shellcheck
      run: sudo apt-get install -y shellcheck
    - name: clone checknr
      run: git clone https://github.com/lcn2/checknr.git
    - name: install checknr
      run: cd checknr && sudo make install
    - name: make test
      run: make test
